services:
  - type: web
    name: gde-tort-api
    runtime: node
    rootDir: apps/api
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /api/auth/me
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4010
      - key: API_PREFIX
        value: api
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 8h
      - key: WEB_ORIGIN
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_NAME
        sync: false
